exclude: .*migrations\/.*

repos:
-   repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
        files: "\\.html"
        types_or: ['html']
      - id: djlint-django
        files: "\\.html"
        types_or: ['html']

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
    -   id: black
        language_version: python3.
