# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-01-26 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConcertStatus', models.CharField(choices=[('OV', 'Over'), ('FS', 'For Sale'), ('UC', 'Upcoming'), ('SO', 'Sold Out'), ('NY', 'Not Yet')], max_length=2)),
            ],
        ),
    ]
