# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-01-26 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_concert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='ConcertStatus',
            new_name='Concert_Status',
        ),
    ]
