# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-01-26 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20240126_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_Type_Label', models.CharField(max_length=40)),
                ('Ticket_ID', models.CharField(max_length=40)),
                ('Linked_Tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Ticket_Type')),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='Concert_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
