# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-01-26 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20240126_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_type',
            name='Linked_Tickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Ticket_Type'),
        ),
    ]
