# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-01-26 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20240126_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_type',
            old_name='Ticket_Type_Label',
            new_name='name',
        ),
    ]
