# Generated by Django 4.2 on 2024-01-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_concert_id_alter_ticket_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_type',
            name='Linked_Tickets',
        ),
        migrations.AddField(
            model_name='ticket_type',
            name='Linked_Tickets',
            field=models.ManyToManyField(to='website.ticket_type'),
        ),
    ]
