# Generated by Django 4.2 on 2024-01-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_ticket_type_linked_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_type',
            name='Linked_Tickets',
            field=models.ManyToManyField(blank=True, to='website.ticket_type'),
        ),
    ]
