# Generated by Django 4.2 on 2024-01-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_ticket_type_linked_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_type',
            name='Linked_Tickets',
            field=models.ManyToManyField(blank=True, help_text='This should auto-populate when saving as long as the STRIPE products and prices are set up correctly. If this does not happen it may be done manually here. However it is not recommended.', to='website.ticket_type'),
        ),
    ]
