# Generated by Django 4.2 on 2024-01-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_ticket_type_linked_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_type',
            name='for_concert',
            field=models.OneToOneField(default=None, help_text='Please select the matching concert here. Make sure this is selected or the ticket will not show.', on_delete=django.db.models.deletion.SET_DEFAULT, to='website.concert'),
        ),
        migrations.AlterField(
            model_name='ticket_type',
            name='Ticket_ID',
            field=models.CharField(help_text="This will be the price ID supplied by STRIPE which you can obtain via the treasurer. Refer to the webmaster bible's payments section for more information", max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket_type',
            name='ticket_label',
            field=models.CharField(help_text="This will be the ticket name shown to the audience (i.e. 'Standard Seating' or 'Concession Seating' or 'Restricted View'", max_length=40),
        ),
    ]
