# Generated by Django 4.2 on 2024-01-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_ticket_type_for_concert'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_label', models.CharField(help_text="This will be the ticket name shown to the audience (i.e. 'Standard Seating' or 'Concession Seating' or 'Restricted View')", max_length=40)),
                ('Ticket_ID', models.CharField(help_text="This will be the price ID supplied by STRIPE which you can obtain via the treasurer. Refer to the webmaster bible's payments section for more information", max_length=40)),
                ('Linked_Tickets', models.ManyToManyField(blank=True, help_text='This should auto-populate when saving as long as the STRIPE products and prices are set up correctly. If this does not happen it may be done manually here. However it is not recommended.', to='website.tickettype')),
                ('for_concert', models.OneToOneField(default=None, help_text='Please select the matching concert here. Make sure this is selected or the ticket will not show.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='website.concert')),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket_Type',
        ),
    ]
