# Generated by Django 4.2 on 2024-01-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_tickettype_delete_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='Concert_Nickname',
            field=models.CharField(default='Concert', help_text='This is just a nickname for this concert to make it easier for you to distinguish in the admin page.', max_length=15),
        ),
    ]
