# Generated by Django 4.2 on 2024-01-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_concert_concert_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='for_concert',
            field=models.OneToOneField(default=None, help_text='Please select the matching concert here. Make sure this is selected or the ticket will not show.', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.concert'),
        ),
    ]
