# Generated by Django 4.2 on 2024-01-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_ticket_name_ticket_email_ticket_forconcert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Email',
            field=models.CharField(default='', help_text="Customer's Email", max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Name',
            field=models.CharField(default='', help_text="Customer's Name", max_length=60),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='TransactionID',
            field=models.CharField(default='', help_text='Autogenerated transaction ID from STRIPE', max_length=100),
        ),
    ]
