# Generated by Django 4.2 on 2024-01-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_rename_transaction_id_ticket_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='change_log',
            field=models.TextField(blank=True, default='', help_text='Will log any changes by automatic systems. I recommend adding any changes here if editing manually.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.tickettype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='validity',
            field=models.BooleanField(default=True, help_text='If tickets, this ticket is valid.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='for_concert',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.concert'),
        ),
    ]
