# Generated by Django 4.2 on 2024-01-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_ticket_change_log_ticket_ticket_type_ticket_validity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='validity',
            field=models.BooleanField(default=True, help_text='If ticked, this ticket is valid.'),
        ),
    ]
