# Generated by Django 4.2 on 2024-01-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_ticket_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='for_concert',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.concert'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.tickettype'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='for_concert',
            field=models.ForeignKey(default=None, help_text='Please select the matching concert here. Make sure this is selected or the ticket will not show.', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.concert'),
        ),
    ]
