# Generated by Django 4.2 on 2024-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_ticket_for_concert_alter_ticket_ticket_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='Ticket_ID',
            new_name='Price_ID',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='Quantity_Available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
