# Generated by Django 4.2 on 2024-01-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_rename_ticket_id_tickettype_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='Product_ID',
            field=models.CharField(blank=True, default='', help_text='This data is automatically taken from STRIPE', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='Quantity_Available',
            field=models.IntegerField(blank=True, default=0, help_text='This data is automatically taken from STRIPE metadata', null=True),
        ),
    ]
