# Generated by Django 4.2 on 2024-01-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_tickettype_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='Quantity_Available',
            new_name='Total_ticket_count',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='Quantity_available',
            field=models.IntegerField(blank=True, default=0, help_text='This populates automatically (Total - sold)', null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='Quantity_sold',
            field=models.IntegerField(blank=True, default=0, help_text='This populates automatically', null=True),
        ),
    ]
