# Generated by Django 4.2 on 2024-01-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_rename_quantity_available_tickettype_total_ticket_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='Linked_sold',
            field=models.IntegerField(blank=True, default=0, help_text='This populates automatically', null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='Quantity_available',
            field=models.IntegerField(blank=True, default=0, help_text='This populates automatically (Total - sold - linked_sold)', null=True),
        ),
    ]
