# Generated by Django 4.2 on 2024-01-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_tickettype_linked_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='Product_ID',
        ),
    ]
