# Generated by Django 4.2 on 2024-01-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_concert_concert_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='display_ticket',
            field=models.BooleanField(default=False, help_text='When ticked, this will show as a purchasable ticket. This should only be false for complimentary tickets.'),
        ),
    ]
