# Generated by Django 4.2 on 2024-01-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_alter_concert_concert_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='Tickets_in_database',
            field=models.IntegerField(blank=True, default=0, help_text='This populates automatically by counting the number of tickets in the database.', null=True),
        ),
    ]
