# Generated by Django 4.2 on 2024-01-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_tickettype_tickets_in_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='position',
            field=models.IntegerField(default=0, help_text='(Lower value shows first)'),
        ),
    ]
