# Generated by Django 4.2 on 2024-01-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_ticket_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='position',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='position',
            field=models.IntegerField(default=0, help_text='(Lower value shows first)'),
        ),
    ]
