# Generated by Django 4.2 on 2024-02-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_remove_ticket_position_tickettype_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='Total_ticket_count',
            field=models.IntegerField(blank=True, default=0, help_text='This is the total number of tickets that should be available for this type. This should be the same across linked tickets.', null=True),
        ),
    ]
